#!/usr/bin/env bash
# install nginx on your web-01 server
# Nginx should be listening on port 80

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
new_string="\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n}"
sed -i "s/^}$/$new_string/" /etc/nginx/sites-available/default
service nginx restart
